### ISSUE TITLE
Missing `axe_env.step_normalize`

### ISSUE THREAD

**Issue by lbenz-mdsol** [tidymodels/butcher#192]
It seems as those the size of recipes can grow very quickly when saving the same exact recipe within vs. outside of a function. This is true even after using `butcher` on the recipes themselves. On some examples I've worked out with large datasets inside of a function, the difference can be ~ 600Kb vs. 30 Gb. This issue is related to an [issue here](https://github.com/tidymodels/recipes/issues/503) but it doesn't quite seem like butcher entirely fixes this issue specifically when saving recipes inside of a function.

Here is a simple reproducible example using the iris data set. 
```
library(recipes)
#> Loading required package: dplyr
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(butcher)
library(readr)
library(fs)

### Save Recipe Outside of Function
rec <- 
  recipe(Species ~ ., data = iris) %>% 
  step_normalize(all_numeric()) %>% 
  step_pca(all_numeric()) %>% 
  prep()

rec <- butcher(rec)
write_rds(rec, 'recipe_outside_of_function.rds')

### Save Recipe inside of Function
my_function <- function() {
  rec <- 
    recipe(Species ~ ., data = iris) %>% 
    step_normalize(all_numeric()) %>% 
    step_pca(all_numeric()) %>% 
    prep()
  
  rec <- butcher(rec)
  write_rds(rec, 'recipe_inside_of_function.rds')
}
my_function()


### Save Recipe inside of Funtion
my_function2 <- function() {
  a <- iris
  b <- iris
  c <- iris
  rec <- 
    recipe(Species ~ ., data = iris) %>% 
    step_normalize(all_numeric()) %>% 
    step_pca(all_numeric()) %>% 
    prep()
  
  rec <- butcher(rec)
  write_rds(rec, 'recipe_inside_of_function_more_stuff.rds')
}
my_function2()

files <- c('recipe_outside_of_function.rds',
           'recipe_inside_of_function.rds',
           'recipe_inside_of_function_more_stuff.rds')

### Print File Sizes
file_size(files)           
#> 18.7K 30K 47.1K
```

As we can see, the same exact recipe, even after being butchered, is different sizes on disk. Furthermore, the more stuff we do inside of the function, the larger the recipe seems to grow, even if such steps are completely unrelated to the recipe itself. Thanks for the help and let me know if anything else can be provided in this example!

**Comment by lbenz-mdsol** [comment]
Seems like this is an issue in other steps too. Here is `step_novel` and `step_mutate_at`, each with the same issue. There are some steps where it doesn't seem to cause memory to grow, but I haven't tested all possible steps by any means.

```{r}
library(recipes)
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(butcher)
library(readr)
library(fs)

### Save Recipe Outside of Function
rec <- 
  recipe(Sepal.Length ~ ., data = iris) %>% 
  step_unknown(Species) %>% 
  prep()

rec <- butcher(rec)
write_rds(rec, 'recipe_outside_of_function.rds')

### Save Recipe inside of Function
my_function <- function() {
  rec <- 
    recipe(Sepal.Length ~ ., data = iris) %>% 
    step_unknown(Species) %>% 
    prep()
  
  rec <- butcher(rec)
  write_rds(rec, 'recipe_inside_of_function.rds')
}
my_function()


### Save Recipe inside of Funtion
my_function2 <- function() {
  a <- iris
  b <- iris
  c <- iris
  rec <- 
    recipe(Sepal.Length ~ ., data = iris) %>% 
    step_unknown(Species) %>% 
    prep()
  
  rec <- butcher(rec)
  write_rds(rec, 'recipe_inside_of_function_more_stuff.rds')
}
my_function2()

files <- c('recipe_outside_of_function.rds',
           'recipe_inside_of_function.rds',
           'recipe_inside_of_function_more_stuff.rds')

### Print File Sizes
file_size(files)           
#> 17.3K 27.3K 44.5K
```


```
library(recipes)
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(butcher)
library(readr)
library(fs)

### Save Recipe Outside of Function
rec <- 
  recipe(Sepal.Length ~ ., data = iris) %>% 
  step_mutate_at(all_nominal(), fn = ~as.numeric(as.factor(.x))) %>%
  prep()

rec <- butcher(rec)
write_rds(rec, 'recipe_outside_of_function.rds')

### Save Recipe inside of Function
my_function <- function() {
  rec <- 
    recipe(Sepal.Length ~ ., data = iris) %>% 
    step_mutate_at(all_nominal(), fn = ~as.numeric(as.factor(.x))) %>%
    prep()
  
  rec <- butcher(rec)
  write_rds(rec, 'recipe_inside_of_function.rds')
}
my_function()


### Save Recipe inside of Funtion
my_function2 <- function() {
  a <- iris
  b <- iris
  c <- iris
  rec <- 
    recipe(Sepal.Length ~ ., data = iris) %>% 
    step_mutate_at(all_nominal(), fn = ~as.numeric(as.factor(.x))) %>%
    prep()
  
  rec <- butcher(rec)
  write_rds(rec, 'recipe_inside_of_function_more_stuff.rds')
}
my_function2()

files <- c('recipe_outside_of_function.rds',
           'recipe_inside_of_function.rds',
           'recipe_inside_of_function_more_stuff.rds')

### Print File Sizes
file_size(files)           
#> 17.1K 26.8K 43.9K
```

**Comment by topepo** [comment]
There are almost 70 steps that don't have specific methods. We'll make an `axe_env.step()` function to cover the `terms` (if any) and find any others that need more than that.

**Comment by ddixonAI** [comment]
Hi. Is there an interim solution to this? Some method by which to eliminate the junk environment manually? I'd like to use my trained recipe object to preprocess my data for a model going into production but the recipe object is several GBs. It contains a normalize step and calling butcher() to the object does not reduce its size. 

Thanks.

**Comment by juliasilge** [comment]
Unfortunately there is not a workaround 😔 but this is increasingly a problem for users like you putting tidymodels in production, so there is urgency to prioritize this problem. Let's see if we can make the change for `axe_env.step` to nuke the `terms` environments, similar to the other `axe_env.step_*` methods:

https://github.com/tidymodels/butcher/blob/f4b0d39dc793e257de965fb355aa8cd95e2454ee/R/recipe.R#L70-L72

**Comment by ddixonAI** [comment]
I was able to manually set the terms components to NULL for the step that was causing me issues, which I located by calling weigh(). Doing it reduced the size on disk from ~10GB to ~500MB (compressed with saveRDS()) so that's a big improvement. But I need to test this modified recipe out a bit so that I'm sure I didn't unintentionally break any functionality.

**Comment by juliasilge** [comment]
@ddixonAI You can install the development version of butcher from GitHub and this should be up and working now:

```r
devtools::install_github("tidymodels/butcher")
```

**Comment by ddixonAI** [comment]
@juliasilge this worked! 

Using the dev butcher, the recipe object is *almost* the exact same size on disk as my manual axe job, the difference probably not worth worrying over. 

Thanks, you guys rock.
