### ISSUE TITLE
glm methods appears broken on dev

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/butcher#233]
I'm no longer able to reproduce the results shown in https://github.com/tidymodels/butcher/pull/212, despite no changes in the `glm.R` file.

I found this problem when trying to answer this SO question https://stackoverflow.com/questions/73529453/file-size-of-tidymodels-workflow

``` r
library(butcher)

more_cars <- mtcars[rep(1:32, each = 1000),]
cars_glm <- glm(mpg ~ ., data = more_cars)
weigh(cars_glm)
#> # A tibble: 63 × 2
#>    object             size
#>    <chr>             <dbl>
#>  1 qr.qr             5.36 
#>  2 y                 2.80 
#>  3 residuals         2.80 
#>  4 fitted.values     2.80 
#>  5 linear.predictors 2.80 
#>  6 weights           2.80 
#>  7 prior.weights     2.80 
#>  8 effects           0.513
#>  9 model.mpg         0.256
#> 10 model.cyl         0.256
#> # … with 53 more rows
#> # ℹ Use `print(n = ...)` to see more rows

butchered <- butcher(cars_glm)
sum(weigh(cars_glm)$size)
#> [1] 28.325
sum(weigh(butchered)$size)
#> [1] 19.91117
weigh(butchered)
#> # A tibble: 53 × 2
#>    object             size
#>    <chr>             <dbl>
#>  1 qr.qr             5.36 
#>  2 residuals         2.80 
#>  3 linear.predictors 2.80 
#>  4 weights           2.80 
#>  5 prior.weights     2.80 
#>  6 effects           0.513
#>  7 model.mpg         0.256
#>  8 model.cyl         0.256
#>  9 model.disp        0.256
#> 10 model.hp          0.256
#> # … with 43 more rows
#> # ℹ Use `print(n = ...)` to see more rows
```

<sup>Created on 2022-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by juliasilge** [comment]
Really wide data can be tough for many kinds of models including tree-based models. I think I'd look at something like lasso or ridge regularization in that situation, either with [glmnet](https://parsnip.tidymodels.org/reference/details_logistic_reg_glmnet.html) or [LiblineaR](https://parsnip.tidymodels.org/reference/details_logistic_reg_LiblineaR.html). LiblineaR is [really fast](https://twitter.com/juliasilge/status/1374029310764359681).

Good luck!
