### ISSUE TITLE
A few additional axe methods for tidymodels

### ISSUE THREAD

**Issue by topepo** [tidymodels/butcher#234]
Some models fit by tidymodels without butcher capabilities:

- [x] `survival::coxph()`
- [x] `mda::fda()`
- [ ] `baguette::bag_*()`
- [x] `ipred::bagging()`
- [x] `dbarts::bart()`
- [x] `MASS::lda()`, `MASS::qda()`
- [x] `klaR::rda()`, `klaR::NaiveBayes()`
- [x] `mixOmics::{s}pls{da}()` (in Bioconductor)
- [x] `xrf::xrf()`

I can make these into separate issues if you like.

**Comment by simonpcouch** [comment]
Upon merge of #249, I believe this issue can be closed!

I haven't put in a PR to address the noted `baguette` entry as those functions seem to integrate their own butcher methods internally. With CART, for example, [this `axe` function](https://github.com/tidymodels/baguette/blob/0a5715952916d080bc4d80c2949c902ebb1ec96c/R/cart.R#L138-L144) is [called at fit time](https://github.com/tidymodels/baguette/blob/0a5715952916d080bc4d80c2949c902ebb1ec96c/R/cart.R#L34-L38) as long as `reduce = TRUE` in `baguette::control_bag()`, which is [the default](https://github.com/tidymodels/baguette/blob/0a5715952916d080bc4d80c2949c902ebb1ec96c/R/bagger.R#L270-L275).

**Comment by juliasilge** [comment]
Thank you so much for these PRs @simonpcouch! 💥 

We can add further methods if/when more needed ones come up.
