### ISSUE TITLE
Don't ship `butcher.png` in the package

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/butcher#257]
Because it is huge, nearly 1mb. The jump from 283kb to 1mb is when we added the logo

<img width="349" alt="Screen Shot 2023-04-03 at 11 30 33 AM" src="https://user-images.githubusercontent.com/19150088/229557413-dc967f6c-b430-4936-a10b-38fff97c8d11.png">

Two things to do:
- Remove `butcher.png` from the package https://github.com/tidymodels/butcher/tree/main/man/figures
- Run `usethis::use_tidy_logo()` to also resize `logo.png`, which is also much too large

**Comment by juliasilge** [comment]
Related to #253

**Comment by juliasilge** [comment]
Closed in #258
