### ISSUE TITLE
Show `butcher()` on README

### ISSUE THREAD

**Issue by hfrick** [tidymodels/butcher#266]
I would have expected to find `butcher()` in the overall intro example. Instead, the README currently suggests that you have to `weigh()` your object and then select the appropriate `axe_*()` call(s).

**Comment by juliasilge** [comment]
Yeah, the documentation as it is right now seems oriented to a developer/contributor rather than a user.

**Comment by hfrick** [comment]
It does mention `butcher()` further down in the text but skimming the example code chunks, I totally missed that in round 1.
